# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hermes < Formula
  desc ""
  homepage ""
  version "1.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/slackapi/slack-cli/releases/download/v1.0.1/hermes_1.0.1_macOS_64-bit.tar.gz"
    sha256 "f4995045c050714172e660a4caf3f47b78c65fcdb73d7c448c194979a1b73e37"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/slackapi/slack-cli/releases/download/v1.0.1/hermes_1.0.1_linux_64-bit.tar.gz"
    sha256 "dd5692ec3e00f76f63c0d929bbef80d7b4668e601def419ba402acc291e00759"
  end

  depends_on "git"

  def install
    bin.install "hermes"
  end
end
