# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hermes < Formula
  desc ""
  homepage ""
  version "1.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/slackapi/slack-cli/releases/download/v0.17.2/hermes_0.17.2_macOS.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "74dfbd3c8801867b4ad56d6fca7e80137144c6e8df08f1ae2fd2556d85fedf66"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/slackapi/slack-cli/releases/download/v0.17.2/hermes_0.17.2_linux_64-bit.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "6ba7745f6ba1a30b102f82d55f4c512e79b175ed2cf7ec967f99c690d13049fb"
  end

  depends_on "git"

  def install
    bin.install "hermes"
  end
end
